name: Run Python Tests

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run tests
      run: |
        cd check_tests/
        python3 check_test.py
    - name: Install GCC
      run: sudo apt-get install -y gcc
  
    - name: Compile C code
      run: |
          gcc -o check_test/check_test_on_c_lang check_tests/check_test_on_c.c -I tasks/ tasks/monotonic_list.c
  
    - name: Run C tests
      run: |
  
          cd check_test
          ./check_test_on_c_lang > output.log
          # Пример проверки выхода:
          if ! grep -q "Expected output" output.log; then
            echo "Test failed"
            exit 1
          fi